### ISSUE TITLE
Table corrupted on column removal?

### ISSUE THREAD

**Issue by MeteC** [editfmah/sharkorm#115]
Hello,

Recently I've been trying to update some tables and have found that I run into permanent database errors (once per fetch) if I ever remove a field from a SRK object. 

e.g. `'no such column: Person.name'` - when "name" in this example is *not* the field I've deleted, and should definitely be there (it is still in the class header).

* Is there a way to remove columns I should be aware of?
* Is there a way to easily check the actual table structures behind the scenes?

It seems adding columns works fine - I can test this by freshly installing my app, then adding a field name `tempField` to my SRK object class, running the app again, then removing `tempField` again and re-running. This causes the errors to start appearing.

I got this error on devices running iOS 12.0.1 and 11.4.1, I don't remember it happening in the past but perhaps I coincidentally haven't removed any fields before!

**Comment by editfmah** [comment]
Nope they should definitely get cleaned up.  I'll have to run up a few unit tests to make sure something isn't broken.

**Comment by editfmah** [comment]
You could execute a raw query with the following pragma.

https://www.sqlite.org/pragma.html#pragma_table_info

This will tell you what state the structure is in.

**Comment by editfmah** [comment]
@MeteC  Okay, looks like we have something weird going on.  I have the same issue in one of our big projects.  Just fixing it now.

**Comment by MeteC** [comment]
Ah good to hear! Thanks Adrian :-)

**Comment by editfmah** [comment]
okay, fixed it.  I'll push a new version once it's been thoroughly tested.  Was quite hard to find, but ended up being a simple fix in the end.

**Comment by editfmah** [comment]
Hi @MeteC, this has been fixed in v2.3.66 available under the releases tab.

**Comment by MeteC** [comment]
Awesome thanks! Any plan to release it for CocoaPods?

**Comment by editfmah** [comment]
Should be automatic from the build server, let me take a look.

**Comment by usman-whizpool** [comment]
hi.. update of v2.3.66 still not available.. just install latest one which is (2.3.62).

**Comment by MeteC** [comment]
Update / FYI: So I've been trying to get the best way to import SharkORM into my project since CocoaPods (still) isn't serving up the latest version. I had just downloaded the latest framework and had imported that into my project, but I wanted to do some more in-depth debugging sessions. So I went back to CooaPods and tried:

`pod 'SharkORM', :git => 'https://github.com/sharksync/sharkorm.git'`

Which caused CocoaPods to crash spectacularly - I filed a report with them on that issue if it's interesting: https://github.com/CocoaPods/CocoaPods/issues/8785

I noticed the branches for latest builds in place, so out of curiosity I then tried:

`pod 'SharkORM', :git => 'https://github.com/sharksync/sharkorm.git', :branch => 'builds/v2.3.67'`

with success!

I wonder if this CocoaPods crash on "Malformed version number string {VER}" has anything to do with the reason CocoaPods isn't able to serve up the latest SharkORM correctly? Anyway, HTH

**Comment by MeteC** [comment]
From the CocoaPods guys: [{VER} isn't a real semantic version number](https://github.com/sharksync/sharkorm/blob/master/SharkORM.podspec#L10), and so it fails. You should probably send a PR to that repo and make it a normal version.

**Comment by editfmah** [comment]
It might be, i'll investigate that as it's driven me nuts for months now.  Thanks for the feedback and information.   SharkORM is going to have a few maintenance revisions over the next few weeks, mainly around interop with swift 5, but there is also the skeleton of [SwiftyShark](https://github.com/sharksync/SwiftyShark) coming along, but it's fundamentally very tricky to achieve lots of the parts of the original ORM without dynamic dispatch.

I was aware that {VER} would not work, but always checked in the branch.
